/* OBLIGATOIREMENT APRES NVINDIVIDU, NVFILM*/

CREATE TABLE NVACTEUR
(
	NUMFILM      INTEGER	NOT NULL,
	NUMINDIVIDU  INTEGER	NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          272K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE NVACTEUR ADD (
  PRIMARY KEY
 (NUMFILM, NUMINDIVIDU)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          432K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE NVACTEUR ADD (
  FOREIGN KEY (NUMFILM) 
 REFERENCES NVFILM (NUMFILM));

ALTER TABLE NVACTEUR ADD (
  FOREIGN KEY (NUMINDIVIDU) 
 REFERENCES NVINDIVIDU (NUMINDIVIDU));


GRANT SELECT ON  NVACTEUR TO ETU4_ROLE;

GRANT SELECT ON  NVACTEUR TO PUBLIC WITH GRANT OPTION;
GRANT REFERENCES ON  NVACTEUR TO PUBLIC;
SET DEFINE OFF;