/* DEUXIEME TABLE A CREER*/

CREATE TABLE NVFILM
(
	NUMFILM		INTEGER,
	TITRE       VARCHAR2(50 BYTE)	NOT NULL,
	REALISATEUR	INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          536K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE NVFILM ADD (
  PRIMARY KEY
 (NUMFILM)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          272K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE NVFILM ADD (
  FOREIGN KEY (REALISATEUR) 
 REFERENCES NVINDIVIDU (NUMINDIVIDU));


GRANT SELECT ON  NVFILM TO ETU4_ROLE;

GRANT SELECT ON  NVFILM TO PUBLIC WITH GRANT OPTION;
GRANT REFERENCES ON  NVFILM TO PUBLIC;
SET DEFINE OFF;