/* OBLIGATOIREMENT APRES NVINDIVIDU, NVFILM*/

CREATE TABLE NVGENREFILM
(
	NUMFILM		INTEGER,
	CODEGENRE	CHAR(2 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          240K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE NVGENREFILM ADD (
  PRIMARY KEY
 (NUMFILM, CODEGENRE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          328K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE NVGENREFILM ADD (
  FOREIGN KEY (NUMFILM) 
 REFERENCES NVFILM (NUMFILM));

ALTER TABLE NVGENREFILM ADD (
  FOREIGN KEY (CODEGENRE) 
 REFERENCES ENS2004.GENRE (CODEGENRE));


GRANT SELECT ON  NVGENREFILM TO ETU4_ROLE;

GRANT SELECT ON  NVGENREFILM TO PUBLIC WITH GRANT OPTION;
GRANT REFERENCES ON  NVGENREFILM TO PUBLIC;
SET DEFINE OFF;